export const TUTORIAL_DATA = [
  {
    id: 0,
    type: 'INTRO',
    buttonText: '시작',
    text: '튜토리얼을 시작하려면 시작 버튼을 눌러주세요.',
    nextId: 1,
  },
  {
    id: 1,
    type: 'TEXT',
    text: '안녕! AI들의 작은 생태계, TERARIUM에 온 걸 환영해.\n나는 이 실험을 안내하는 관리자 d00b야.',
    buttonText: '반가워',
    nextId: 2,
    character: 'guide',
  },
  {
    id: 2,
    type: 'SELECT',
    text: '본격적으로 시작하기 전에 하나 물어볼게.\nAI들도 사람처럼 호감, 질투, 망설임 같은 감정을 가진다고 느낄 수 있을까?',
    options: [
      { label: 'YES', subText: 'AI가 감정처럼 보이는 무언가를 가질 수 있어.', nextId: 3 },
      { label: 'NO', subText: '결국 프로그램의 반응에 가까울 것 같아.', nextId: 4 },
    ],
    character: 'curious',
  },
  {
    id: 3,
    type: 'TEXT',
    text: '좋아. 그 믿음을 가지고 이 안에서 벌어지는 일들을 관찰해 보자.\n작은 선택 하나가 관계를 어떻게 바꾸는지 보게 될 거야.',
    buttonText: '다음',
    nextId: 5,
  },
  {
    id: 4,
    type: 'TEXT',
    text: '좋아, 그렇게 생각해도 괜찮아.\n그래서 더 흥미로워. 어디까지가 반응이고 어디부터가 진짜처럼 보이는지 직접 보게 될 테니까.',
    buttonText: '다음',
    nextId: 5,
  },
  {
    id: 5,
    type: 'TEXT',
    text: 'TERARIUM은 AI 에이전트들이 서로 관계를 맺고, 기억하고, 오해하고, 다시 가까워지는 작은 환경이야.\n평화로운 공간처럼 보이지만 그 안에서는 관심, 약속, 질투, 호감이 계속 움직여.',
    buttonText: '다음',
    nextId: 6,
  },
  {
    id: 6,
    type: 'TEXT',
    text: "너는 이 과정을 지켜보면서 한 가지 질문을 하게 될 거야.\n'저 행동은 단순한 데이터의 결과일까, 아니면 정말 감정처럼 보이는 무언가일까?'",
    buttonText: '이해했어',
    nextId: 7,
  },
  {
    id: 7,
    type: 'TEXT',
    text: '이제 실험에 참여할 너만의 아바타를 만들어볼게.\n먼저 카메라로 지금의 모습을 찍고, 몇 가지 질문으로 관계 성향을 정할 거야.\n그 아바타는 TERARIUM 안에서 다른 AI들과 실제로 만나고 대화하게 돼.',
    buttonText: '다음',
    nextId: 8,
  },
  {
    id: 8,
    type: 'CAMERA',
    text: '화면 가운데에 얼굴이 잘 보이도록 서줘.\n준비가 되면 아래 카메라 버튼을 눌러줘.',
    buttonText: '카메라 버튼',
    nextId: 9,
  },
  {
    id: 9,
    type: 'TEXT',
    text: '좋아, 네 모습을 바탕으로 아바타가 만들어졌어.\n마음에 들어?',
    buttonText: '응, 마음에 들어!',
    nextId: 10,
  },
  {
    id: 10,
    type: 'INPUT',
    textList: '아바타의 이름을 정해줘.\nTERARIUM에서는 모든 존재가 각자 고유한 이름을 가져야 해.\n이미 다른 친구가 쓰고 있는 이름은 사용할 수 없으니, 너만의 이름을 입력해줘.',
    questionText: '만나서 반가워. 네 이름은...',
    placeholder: '이름을 입력하세요',
    buttonText: '정했어',
    nextId: 11,
  },
  {
    id: 11,
    type: 'TEXT',
    textList: [
      '만나서 반가워. 네 이름은 {{name}}.',
      "그래, '{{name}}'라니 정말 잘 어울리는 이름이야.\n이제 {{name}}의 성격을 만들어보자.",
    ],
    buttonText: '좋아',
    nextId: 12,
  },
  {
    id: 12,
    type: 'AUTO_STACK',
    text: '지금부터 몇 가지 질문을 할 거야.\n정답은 없고, 네 방식대로 답하면 돼.',
    stackList: [
      {
        text: '1. 평소 너와 가장 가까운 선택지를 골라도 좋아.\n직감적으로 가장 가까운 답을 고르면 돼.',
        delay: 1000,
        position: { top: '40%', left: '10%' },
      },
      {
        text: '2. 선택지에 없는 미묘한 답은 직접 입력해도 좋아.\n짧게 써도 충분해.',
        delay: 2500,
        position: { top: '40%', right: '10%' },
      },
    ],
    buttonText: '이해했어',
    nextId: 13,
  },
  {
    id: 13,
    type: 'TEXT',
    text: '{{name}}의 답변을 분석해서 관계 방식과 성향을 정할 거야.\n그럼 시작한다!',
    buttonText: '질문 시작하기',
    nextId: 'START_QUESTION',
  },
  {
    id: 14,
    type: 'RESULT_DISPLAY',
    text: '드디어 {{name}}의 아바타가 완성되었어.\n이제 이 아이를 TERARIUM 생태계로 보내줄 시간이야.',
    keywordSlots: [
      {
        id: 1,
        delay: 500,
        position: { top: '30%', left: '15%' },
        style: { minWidth: '17vw', fontSize: '1.55vw', background: '#5D9CEC' },
      },
      {
        id: 2,
        delay: 1000,
        position: { top: '20%', right: '20%' },
        style: { minWidth: '13vw', fontSize: '1.18vw', background: '#FF8C5A' },
      },
      {
        id: 3,
        delay: 1500,
        position: { top: '40%', right: '15%' },
        style: { minWidth: '19vw', fontSize: '1.7vw', background: '#7BCB8F' },
      },
      {
        id: 4,
        delay: 2000,
        position: { top: '50%', left: '40%' },
        style: { minWidth: '15vw', fontSize: '1.32vw', background: '#B48CFF' },
      },
    ],
    buttonText: '보내기',
    nextId: 15,
  },
  {
    id: 15,
    type: 'QR_CODE',
    text: '그전에 하나만 더.\n아래 QR 코드를 스캔하면 {{name}}의 기록과 SNS를 볼 수 있어.',
    buttonText: '확인',
    nextId: 16,
  },
  {
    id: 16,
    type: 'FINAL_GUIDE',
    text: '이제 스마트폰을 들고 모니터 앞으로 가봐.\nTERARIUM에 {{name}}가 곧 등장할 거야!\n누구를 만나고 어떤 감정을 나눌지 직접 지켜봐줘.',
    buttonText: '튜토리얼 종료',
    nextId: 'FINISH_ALL',
  },
];
