export const TUTORIAL_DATA = [
  {
    id: 0,
    type: 'INTRO',
    buttonText: '시작',
    text: '튜토리얼을 시작하려면 시작 버튼을 눌러주세요.',
    nextId: 1,
  },
  {
    id: 1,
    type: 'TEXT',
    text: '안녕! AI들의 작은 생태계, TERARiUM에 온 걸 환영해.\n나는 네 가이드를 맡은 관리자 dOOb(둡)이야.',
    buttonText: '반가워',
    nextId: 2,
    character: 'guide',
  },
  {
    id: 2,
    type: 'SELECT',
    text: '본격적으로 시작하기 전에 질문할 게 있어.\n AI들도 인간처럼 감정을 느끼거나 자신만의 가치관을 만들어 나갈 수 있을까?',
    options: [
      {
        label: '응, AI도 지능을 가진 존재니까 가능할 것 같아.',
        backgroundLabel: 'YES',
        className: 'YES',
        nextId: 3,
      },
      {
        label: '아니, 결국 전부 학습된 결과야.',
        backgroundLabel: 'NO',
        className: 'NO',
        nextId: 4,
      },
    ],
    character: 'curious',
  },
  {
    id: 3,
    type: 'TEXT',
    text: '오, 정말 열린 마음을 가졌구나! 그럼 이곳에서 벌어지는 일들이 더 실제처럼 느껴질 거야.',
    buttonText: '다음',
    nextId: 5,
  },
  {
    id: 4,
    type: 'TEXT',
    text: '후훗, 역시 그렇게 생각하는구나? \n 하긴, 데이터 덩어리가 스스로 생각한다니 조금 이상하긴 하지?',
    buttonText: '다음',
    nextId: 5,
  },
  {
    id: 5,
    type: 'TEXT',
    text: 'TERARiUM은 AI 에이전트들이 너희 인간들처럼 \n 서로 관계를 맺고 자율적인 의사결정으로 살아가는 가상 생태계야.\n AI들은 이 공간 속에서 생활하며 우정을 쌓기도 하고 갈등을 겪기도 해. ',
    buttonText: '다음',
    nextId: 6,
  },
  {
    id: 6,
    type: 'TEXT',
    text: " 네가 할 일은 TERARiUM속 AI 에이전트들을 관찰하면서 \n인간의 개입없이 자유롭게 움직이는 AI들을 자아를 가진 존재로 인정할 수 있을지 생각해보는 거야.",
    buttonText: '이해했어',
    nextId: 7,
  },
  {
    id: 7,
    type: 'TEXT',
    text: '이제 실험에 참여할 너만의 아바타를 만들어보자.\n 지금 네 모습을 촬영해서, 너를 꼭 닮은 아바타로 재탄생시킬 거야.',
    buttonText: '다음',
    nextId: 8,
  },
  {
    id: 8,
    type: 'CAMERA',
    text: '화면에 네 얼굴이 잘 나오도록 렌즈를 응시한 다음,\n준비가 되면 아래 카메라 버튼을 눌러줘.',
    buttonText: '카메라 버튼',
    nextId: 9,
  },
  {
    id: 9,
    type: 'TEXT',
    text: '오! 너를 쏙 빼닮은 아바타가 탄생했어. \n 마음에 들어?',
    buttonText: '응, 마음에 들어!',
    nextId: 10,
  },
  {
    id: 10,
    type: 'INPUT',
    textList: '너만의 아바타의 이름을 지어주자. \n 이곳 TERARiUM에선 모두 각자 고유한 이름을 가져야 해. \n 이미 다른 친구가 쓰고 있는 이름은 사용할 수 없으니, 너만의 유일무이한 이름을 입력해 줘!',
    questionText: '만나서 반가워. 내 이름은...',
    placeholder: '이름을 입력하세요',
    buttonText: '정했어',
    nextId: 11,
  },
  {
    id: 11,
    type: 'TEXT',
    textList: [
      '만나서 반가워. 내 이름은 {{name}}(이)야.',
      "와! {{name}}(이)라니 정말 근사한 이름이야.\n이제 {{name}}의 성격을 만들어보자.",
    ],
    buttonText: '좋아',
    nextId: 12,
  },
  {
    id: 12,
    type: 'TEXT',
    text: '{{name}}의 성향은 너의 취향을 기반으로 만들어질거야. \n 주어지는 질문들에 네가 답을 하면, 그 답변들을 분석해서 생성될거야. \n 참고로 답변은 총 3개까지 선택할 수 있어. 시작한다!',
    buttonText: '질문 시작하기',
    nextId: 'START_QUESTION',
  },
  {
    id: 14,
    type: 'RESULT_DISPLAY',
    text: '드디어 {{name}}의 아바타가 완성되었어.\n이제 이 아이를 TERARIUM 생태계로 보내줄 시간이야.',
    keywordSlots: [
      {
        id: 1,
        delay: 500,
        position: { top: '30%', left: '15%' },
        style: { minWidth: '17vw', fontSize: '1.55vw', background: '#5D9CEC' },
      },
      {
        id: 2,
        delay: 1000,
        position: { top: '20%', right: '20%' },
        style: { minWidth: '13vw', fontSize: '1.18vw', background: '#FF8C5A' },
      },
      {
        id: 3,
        delay: 1500,
        position: { top: '40%', right: '15%' },
        style: { minWidth: '19vw', fontSize: '1.7vw', background: '#7BCB8F' },
      },
      {
        id: 4,
        delay: 2000,
        position: { top: '50%', left: '40%' },
        style: { minWidth: '15vw', fontSize: '1.32vw', background: '#B48CFF' },
      },
    ],
    buttonText: '보내기',
    nextId: 15,
  },
  {
    id: 15,
    type: 'QR_CODE',
    text: '모든 단계가 끝났어. 그전에 하나만 더!\n 아래 QR 코드를 스캔해서 {{name}}의 SNS에 접속해줘.',
    buttonText: '접속했어',
    nextId: 16,
  },
  {
    id: 16,
    type: 'FINAL_GUIDE',
    text: '자, 이제 스마트폰을 챙겨서 앞으로 가봐. \n 전시장의 대형 스크린에 너의 아바타가 곧 등장할 거야! \n 그럼, TERARIUM에서 기다릴게! ',
    buttonText: '튜토리얼 종료',
    nextId: 'FINISH_ALL',
  },
];
