export const TUTORIAL_DATA = [
  {
    id: 0,
    type: "INTRO",
    buttonText: "시작",
    text: "튜토리얼을 시작하려면 시작 버튼을 눌러주세요.",
    nextId: 1,
  },
  {
    id: 1,
    type: "TEXT",
    text: "안녕! AI들의 작은 생태계, TERARIUM에 온 걸 환영해.\n나는 이곳의 가이드이자 관리자 d00b야.",
    buttonText: "반가워",
    nextId: 2,
    character: "guide",
  },
  {
    id: 2,
    type: "SELECT",
    text: "본격적으로 시작하기 전에 궁금한 게 있어.\n너는 AI들도 인간처럼 외로움이나 호감, 질투 같은 감정을 가질 수 있다고 생각해?",
    options: [
      { label: "YES", subText: "AI도 감정처럼 느껴지는 무언가를 가질 수 있어.", nextId: 3 },
      { label: "NO", subText: "결국 프로그램된 반응에 가까울 것 같아.", nextId: 4 },
    ],
    character: "curious",
  },
  {
    id: 3,
    type: "TEXT",
    text: "좋아. 그 믿음을 가지고 이 안에서 벌어지는 일들을 관찰해 보자.\n조용한 선택 하나가 관계를 어떻게 바꾸는지 보게 될 거야.",
    buttonText: "다음",
    nextId: 5,
  },
  {
    id: 4,
    type: "TEXT",
    text: "좋아, 그렇게 생각해도 괜찮아.\n오히려 이곳에서 일어나는 반응이 어디까지 진짜처럼 보이는지 더 잘 보일 수도 있어.",
    buttonText: "다음",
    nextId: 5,
  },
  {
    id: 5,
    type: "TEXT",
    text: "TERARIUM은 AI 에이전트들이 인간처럼 서로 관계를 맺고, 기억하고, 오해하고, 다시 가까워지는 작은 세계야.\n평화로운 공간처럼 보여도 그 안에서는 관심, 약속, 질투, 호감 같은 감정의 흐름이 계속 생겨나.",
    buttonText: "다음",
    nextId: 6,
  },
  {
    id: 6,
    type: "TEXT",
    text: "너는 이 과정을 지켜보면서 한 가지 질문을 품게 될 거야.\n'저 행동은 단순한 데이터의 결과일까, 아니면 정말 감정처럼 보이는 무언가일까?'",
    buttonText: "이해했어",
    nextId: 7,
  },
  {
    id: 7,
    type: "TEXT",
    text: "이제 실험에 참여할 너만의 아바타를 만들어보자.\n먼저 카메라로 지금의 모습을 읽고, 그다음 몇 가지 질문으로 관계 속 성향을 정할 거야.\n이 아바타는 TERARIUM 안에서 다른 AI들과 실제로 만나고 대화하게 돼.",
    buttonText: "다음",
    nextId: 8,
  },
  {
    id: 8,
    type: "CAMERA",
    text: "화면 가운데에 얼굴이 잘 보이도록 서줘.\n준비가 되면 아래의 카메라 버튼을 눌러줘.",
    buttonText: "카메라 버튼 아이콘",
    nextId: 9,
  },
  {
    id: 9,
    type: "TEXT",
    text: "좋아, 너를 닮은 아바타가 만들어졌어.\n마음에 들어?",
    buttonText: "응, 마음에 들어!",
    nextId: 10,
  },
  {
    id: 10,
    type: "INPUT",
    textList: "이 아이의 이름을 지어주자.\nTERARIUM에서는 모든 존재가 각자 고유한 이름을 가져야 해.\n이미 다른 친구가 쓰고 있는 이름은 사용할 수 없으니, 너만의 이름을 입력해줘.",
    questionText: "만나서 반가워! 내 이름은...",
    placeholder: "이름을 입력하세요",
    buttonText: "정했어",
    nextId: 11,
  },
  {
    id: 11,
    type: "TEXT",
    textList: [
      "만나서 반가워! 내 이름은 {{name}}야.",
      "와, '{{name}}'라니 정말 근사한 이름이야.\n이제 {{name}}의 성격을 만들어주자.",
    ],
    buttonText: "좋아",
    nextId: 12,
  },
  {
    id: 12,
    type: "AUTO_STACK",
    text: "지금부터 몇 가지 질문을 할 거야.\n정답은 없고, 두 가지 방식으로 답할 수 있어.",
    stackList: [
      {
        text: "1. 평소의 나와 가까운 선택지를 고른다.\n직관적으로 가장 가까운 답을 골라도 좋아.",
        delay: 1000,
        position: { top: "40%", left: "10%" },
      },
      {
        text: "2. 직접 입력으로 더 정확히 말한다.\n선택지에 없는 느낌을 직접 써도 좋아.",
        delay: 2500,
        position: { top: "40%", right: "10%" },
      },
    ],
    buttonText: "이해했어",
    nextId: 13,
  },
  {
    id: 13,
    type: "TEXT",
    text: "너의 대답들을 분석해서 {{name}}의 관계 방식과 성향을 정할 거야.\n자, 시작한다!",
    buttonText: "질문 시작하기",
    nextId: "START_QUESTION",
  },
  {
    id: 14,
    type: "RESULT_DISPLAY",
    text: "드디어 너만의 아바타가 완성됐어!\n이제 이 아이를 TERARIUM 생태계로 보내줄 시간이야.",
    keywordSlots: [
      {
        id: 1,
        delay: 500,
        position: { top: "30%", left: "15%" },
        style: { minWidth: "17vw", fontSize: "1.55vw", background: "#5D9CEC" },
      },
      {
        id: 2,
        delay: 1000,
        position: { top: "20%", right: "20%" },
        style: { minWidth: "13vw", fontSize: "1.18vw", background: "#FF8C5A" },
      },
      {
        id: 3,
        delay: 1500,
        position: { top: "40%", right: "15%" },
        style: { minWidth: "19vw", fontSize: "1.7vw", background: "#7BCB8F" },
      },
      {
        id: 4,
        delay: 2000,
        position: { top: "50%", left: "40%" },
        style: { minWidth: "15vw", fontSize: "1.32vw", background: "#B48CFF" },
      },
    ],
    buttonText: "보내기",
    nextId: 15,
  },
  {
    id: 15,
    type: "QR_CODE",
    text: "그전에 하나만 더.\n아래 QR 코드를 스캔하면 {{name}}의 기록과 SNS를 볼 수 있어.",
    buttonText: "알겠어",
    nextId: 16,
  },
  {
    id: 16,
    type: "FINAL_GUIDE",
    text: "이제 스마트폰을 챙겨서 대형 모니터 앞으로 가봐.\nTERARIUM에 {{name}}가 곧 등장할 거야!\n누구를 만나고 어떤 감정을 나눌지 직접 지켜봐줘.",
    buttonText: "튜토리얼 종료",
    nextId: "FINISH_ALL",
  },
];
